/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pharmacommerce.Productos;

import com.mycompany.pharmacommerce.Gui;

/**
 *
 * @author henao
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BotonCrearProducto = new javax.swing.JButton();
        BotonBuscarProducto = new javax.swing.JButton();
        BotonActualizarProducto = new javax.swing.JButton();
        EliminarProductos = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        inicio_menu_productos = new javax.swing.JMenuItem();
        productos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Productos ");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\carrito-de-supermercado.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("¡Bienvenido a la sección de Productos! Aquí, te ofrecemos las herramientas necesarias para gestionar tu inventario de manera eficiente.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Ya sea que necesites consultar información detallada sobre tus productos, agregar nuevos artículos a tu catálogo o eliminar productos existentes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("esta pestaña es tu punto de partida.");

        BotonCrearProducto.setBackground(new java.awt.Color(0, 153, 255));
        BotonCrearProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonCrearProducto.setForeground(new java.awt.Color(255, 255, 255));
        BotonCrearProducto.setText("Crear");
        BotonCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCrearProductoActionPerformed(evt);
            }
        });

        BotonBuscarProducto.setBackground(new java.awt.Color(0, 153, 255));
        BotonBuscarProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscarProducto.setText("Buscar");
        BotonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarProductoActionPerformed(evt);
            }
        });

        BotonActualizarProducto.setBackground(new java.awt.Color(0, 153, 255));
        BotonActualizarProducto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonActualizarProducto.setForeground(new java.awt.Color(255, 255, 255));
        BotonActualizarProducto.setText("Actualizar");
        BotonActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarProductoActionPerformed(evt);
            }
        });

        EliminarProductos.setBackground(new java.awt.Color(0, 153, 255));
        EliminarProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EliminarProductos.setForeground(new java.awt.Color(255, 255, 255));
        EliminarProductos.setText("Eliminar");
        EliminarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BotonCrearProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonActualizarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EliminarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(492, 492, 492))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(53, 53, 53)
                .addComponent(BotonCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EliminarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jMenuBar2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jMenu3.setForeground(new java.awt.Color(0, 204, 204));
        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\logo_32px.png")); // NOI18N
        jMenu3.setText("PharmaCommerce");
        jMenuBar2.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\inicio.png")); // NOI18N
        jMenu4.setText("Inicio");
        jMenuBar2.add(jMenu4);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\nosotros.png")); // NOI18N
        jMenu1.setText("Nosotros");
        jMenuBar2.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\menu.png")); // NOI18N
        jMenu2.setText("Menú");

        inicio_menu_productos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        inicio_menu_productos.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\inicio2.png")); // NOI18N
        inicio_menu_productos.setText("Inicio");
        inicio_menu_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_menu_productosActionPerformed(evt);
            }
        });
        jMenu2.add(inicio_menu_productos);

        productos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        productos.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\productos.png")); // NOI18N
        productos.setText("Productos");
        productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosActionPerformed(evt);
            }
        });
        jMenu2.add(productos);

        jMenuItem3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\compras.png")); // NOI18N
        jMenuItem3.setText("Compras");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\clientes.png")); // NOI18N
        jMenuItem4.setText("Clientes");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\empleados.png")); // NOI18N
        jMenuItem5.setText("Empleados");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\proveedores.png")); // NOI18N
        jMenuItem6.setText("Proveedores");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\categorias.png")); // NOI18N
        jMenuItem7.setText("Categorías");
        jMenu2.add(jMenuItem7);

        jMenuBar2.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\perfil.png")); // NOI18N
        jMenu5.setText("Mi perfil");

        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\configuracion.png")); // NOI18N
        jMenuItem8.setText("Configuración");
        jMenu5.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\editar.png")); // NOI18N
        jMenuItem9.setText("Editar perfil");
        jMenu5.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon("C:\\Users\\henao\\OneDrive\\Documentos\\NetBeansProjects\\PharmaCommerce\\images\\logout.png")); // NOI18N
        jMenuItem10.setText("Cerrar sesión");
        jMenu5.add(jMenuItem10);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicio_menu_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_menu_productosActionPerformed
        // TODO add your handling code here:
        Gui inicioFrame = new Gui();
        inicioFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_inicio_menu_productosActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void BotonCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCrearProductoActionPerformed
        // TODO add your handling code here:
        CrearProductos crearFrame = new CrearProductos();
        crearFrame.setVisible(true);
    }//GEN-LAST:event_BotonCrearProductoActionPerformed
       
    private void productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosActionPerformed
        // TODO add your handling code here:
        Productos productosFrame = new Productos();
        productosFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_productosActionPerformed

    private void BotonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarProductoActionPerformed
        // TODO add your handling code here:
        BuscarProductos buscarFrame = new BuscarProductos();
        buscarFrame.setVisible(true);
    }//GEN-LAST:event_BotonBuscarProductoActionPerformed

    private void BotonActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarProductoActionPerformed
        // TODO add your handling code here:
        ActualizarProductos actualizarFrame = new ActualizarProductos();
        actualizarFrame.setVisible(true);
    }//GEN-LAST:event_BotonActualizarProductoActionPerformed

    private void EliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductosActionPerformed
        // TODO add your handling code here:
        EliminarProductos eliminarFrame = new EliminarProductos();
        eliminarFrame.setVisible(true);
    }//GEN-LAST:event_EliminarProductosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizarProducto;
    private javax.swing.JButton BotonBuscarProducto;
    private javax.swing.JButton BotonCrearProducto;
    private javax.swing.JButton EliminarProductos;
    private javax.swing.JMenuItem inicio_menu_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem productos;
    // End of variables declaration//GEN-END:variables
}
